import type { Member } from "@/types/members";
export const dummyMemberData: Member[] = [
    { id: 1, name: "박진아", generation: "13기", part: "기획", role: "대표" },
    { id: 2, name: "박진아", generation: "13기", part: "디자인", role: "운영진" },
    { id: 3, name: "박진아", generation: "13기", part: "AI", role: "아기사자" },
    { id: 4, name: "김수현", generation: "12기", part: "프론트엔드", role: "아기사자" },
    { id: 5, name: "이지은", generation: "12기", part: "디자인", role: "운영진" },
    { id: 6, name: "박진아", generation: "13기", part: "기획", role: "대표" },
    { id: 7, name: "박진아", generation: "13기", part: "디자인", role: "운영진" },
    { id: 8, name: "박진아", generation: "13기", part: "AI", role: "아기사자" },
    { id: 9, name: "김수현", generation: "12기", part: "프론트엔드", role: "아기사자" },
    { id: 10, name: "이지은", generation: "12기", part: "디자인", role: "운영진" },
    { id: 11, name: "박진아", generation: "13기", part: "기획", role: "대표" },
    { id: 12, name: "박진아", generation: "13기", part: "디자인", role: "운영진" },
    { id: 13, name: "박진아", generation: "13기", part: "AI", role: "아기사자" },
    { id: 14, name: "김수현", generation: "12기", part: "프론트엔드", role: "아기사자" },
    { id: 15, name: "이지은", generation: "12기", part: "디자인", role: "운영진" },
    { id: 16, name: "박진아", generation: "13기", part: "기획", role: "대표" },
    { id: 17, name: "박진아", generation: "13기", part: "디자인", role: "운영진" },
    { id: 18, name: "박진아", generation: "13기", part: "AI", role: "아기사자" },
    { id: 19, name: "김수현", generation: "12기", part: "프론트엔드", role: "아기사자" },
    { id: 20, name: "이지은", generation: "12기", part: "디자인", role: "운영진" },
    { id: 21, name: "박진아", generation: "13기", part: "기획", role: "대표" },
    { id: 22, name: "박진아", generation: "13기", part: "디자인", role: "운영진" },
    { id: 23, name: "박진아", generation: "13기", part: "AI", role: "아기사자" },
    { id: 24, name: "김수현", generation: "12기", part: "프론트엔드", role: "아기사자" },
    { id: 25, name: "이지은", generation: "12기", part: "디자인", role: "운영진" }
];
